# Generated by Django 4.1.7 on 2023-03-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Refrigerant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("code", models.CharField(max_length=64)),
                ("formula", models.CharField(max_length=64)),
                ("molecular_weight", models.CharField(max_length=64)),
                ("curve_data", models.JSONField(default=dict)),
                ("type", models.CharField(max_length=64)),
                ("safety_index", models.CharField(max_length=64)),
                ("env_impact_index", models.CharField(max_length=64)),
            ],
        ),
    ]
